language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin libgdal-dev
  - sudo rm -f /etc/boto.cfg # Solves https://github.com/travis-ci/travis-ci/issues/7940
install:
  - pip install fiona shapely pyproj pyproject aniso8601 contexttimer
script: python setup.py test
branches:
  only:
    - master
