language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin libgdal-dev
install:
  - pip install fiona shapely pyproj pyproject
script: python setup.py test
branches:
  only:
    - master
